import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react"; // ★ 추가
import Script from "next/script";                   // ★ (GA 쓸 때만) 추가

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const GA_ID = process.env.NEXT_PUBLIC_GA_ID; // ★ (선택) GA4 아이디 환경변수

  return (
    <html lang="ko">
      {/* ✅ 모바일 대응 핵심: viewport 메타태그 */}
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* 선택: 브라우저 상단 색상 */}
        <meta name="theme-color" content="#FCFBF9" />
      </head>

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}

        {/* 1) Vercel Analytics (필수) */}
        <Analytics />

        {/* 2) (선택) GA4 gtag — GA 쓸 때만, Vercel 환경변수에 NEXT_PUBLIC_GA_ID 세팅 */}
        {GA_ID && (
          <>
            <Script
              src={`https://www.googletagmanager.com/gtag/js?id=${GA_ID}`}
              strategy="afterInteractive"
            />
            <Script id="ga-init" strategy="afterInteractive">
              {`
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());
                gtag('config', '${GA_ID}', { anonymize_ip: true });
              `}
            </Script>
          </>
        )}
      </body>
    </html>
  );
}
